# Generated by Django 2.2.7 on 2019-11-18 18:16

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='rich_body',
            field=tinymce.models.HTMLField(default=''),
            preserve_default=False,
        ),
    ]
