# Generated by Django 2.2.9 on 2019-12-31 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blog_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image_url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
