# Generated by Django 2.2.9 on 2020-01-01 19:43

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0002_auto_20200101_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='notes',
            field=tinymce.models.HTMLField(default=''),
            preserve_default=False,
        ),
    ]
